import os

EXPORT_CONFIG = {
    'WindowBackground': '#f0f0f0',
    'ButtonWidth': 180,
    'ButtonHeight': 200,
    'ButtonsAmountX': 3,
    'ButtonsAmountY': 3,
    'ButtonFontSize': 25,
    'ButtonImageSize': 100,
    'ButtonForegroundColor': '#535353',
    'ButtonBackgroundColor': '#ffffff',
    'ButtonPressedBackgroundColor': '#c3c3c3',
    'ButtonActiveBackgroundColor': '#ececec',
    'ButtonFramePaddingX': 1,
    'ButtonFramePaddingY': 1,
    'FocusedButtonForegroundColor': '#535353',
    'FocusedButtonBackgroundColor': '#c1c1c1',
    'FocusedButtonPressedForegroundColor': '#b3b3b3',
    'FocusedButtonActiveForegroundColor': '#c1c1c1',
    'ButtonFrameBorderColor': '#e7e7e7',
    'DropdownButtonHeight': 60,
    'DropdownButtonIconSize': 25,
    'SearchLabelHeight': 40,
    'SearchLabelForegroundColor': '#535353',
    'SearchLabelFontSize': 25,
    'SearchLabelIconPaddingX': 30,
    'SearchLabelIconPaddingY': 5,
    'SearchLabelIconSize': 25,
    'SearchLabelIconPath': './ui/search.png',
    'SearchLabelInputPaddingX': 130,
    'SearchLabelInputPaddingY': 5,
    'SearchLabelInputTruncate': 17,
    'RoundBoxHeight': 40,
    'RoundBoxPath': './ui/rounded.png',
    'CanvasBackgroundColor': '#ffffff',
    'CanvasDropdownSpeed': 5,
    'CanvasDropdownFrameSkip': 10,
    'CanvasDropdownReturnSpeed': 7,
    'CanvasDropdownReturnFrameSkip': 10,
    'ButtonKeyUp': {111},
    'ButtonKeyDown': {116},
    'ButtonKeyLeft': {113},
    'ButtonKeyRight': {114},
    'DesktopFolders': ['/usr/share/applications', '/home/' + os.environ['USER'] + '/.local/share/applications'],
    'IconFolders': ['/usr/share/icons', '/usr/share/pixmaps', '/home/' + os.environ['USER'] + '/.local/share/icons'],
    'IconThemes': ['Adwaita', 'hicolor', 'default'],
    'IconResolutions': ['1024x1024', '512x512', '256x256', '192x192', '128x128', '96x96', '72x72', '64x64', '48x48', '42x42', '40x40', '36x36', '32x32', '24x24', '22x22', '20x20', '16x16', '8x8'],
    'IconFormats': ['png', 'xpm', 'svg'],
    'Apps': [
        [None, None, None],
        [None, None, None],
        [None, None, None],
        ],
    'DefaultInstallationFolder': '/home/' + os.environ['USER'] + '/nero-launcher',
    'DefaultConfigFolder': '/home/' + os.environ['USER'] + '/.config/nero-launcher',
    'AppCacheFileLocation': './appcache.json',
}
