CONFIG={
    'WindowBackground': '#282a36',
    'ButtonForegroundColor': '#f8f8f2',
    'ButtonBackgroundColor': '#282a36',
    'ButtonPressedBackgroundColor': '#44475a',
    'ButtonActiveBackgroundColor': '#44475a',
    'FocusedButtonForegroundColor': '#f8f8f2',
    'FocusedButtonBackgroundColor': '#6272a4',
    'FocusedButtonPressedForegroundColor': '#f8f8f2',
    'FocusedButtonActiveForegroundColor': '#f8f8f2',
    'FocusedButtonPressedBackgroundColor': '#44475a',
    'FocusedButtonActiveBackgroundColor': '#44475a',
    'ButtonFrameBorderColor': '#23252f',
    'SearchLabelForegroundColor': '#f8f8f2',
    'SearchLabelBackgroundColor': '#6272a4',
    'SearchLabelIconPath': './ui/search-dracula.png',
    'RoundBoxPath': './ui/rounded-dracula.png',
    'CanvasBackgroundColor': '#2e3440',
}
