CONFIG={
    'WindowBackground': '#000000',
    'ButtonForegroundColor': '#ebdbb2',
    'ButtonBackgroundColor': '#32302f',
    'ButtonPressedBackgroundColor': '#282828',
    'ButtonActiveBackgroundColor': '#3c3836',
    'FocusedButtonForegroundColor': '#ebdbb2',
    'FocusedButtonBackgroundColor': '#1d2021',
    'FocusedButtonPressedForegroundColor': '#ebdbb2',
    'FocusedButtonActiveForegroundColor': '#ebdbb2',
    'FocusedButtonPressedBackgroundColor': '#1d2021',
    'FocusedButtonActiveBackgroundColor': '#1d2021',
    'ButtonFrameBorderColor': '#282828',
    'SearchLabelForegroundColor': '#ebdbb2',
    'SearchLabelBackgroundColor': '#3c3836',
    'SearchLabelIconPath': './ui/search-gruvbox-dark.png',
    'RoundBoxPath': './ui/rounded-gruvbox-dark.png',
    'CanvasBackgroundColor': '#2d2d2d',
}
