CONFIG={
    'WindowBackground': '#2e3440',
    'ButtonForegroundColor': '#eceff4',
    'ButtonBackgroundColor': '#2e3440',
    'ButtonPressedBackgroundColor': '#2e3440',
    'ButtonActiveBackgroundColor': '#3b4252',
    'FocusedButtonForegroundColor': '#eceff4',
    'FocusedButtonBackgroundColor': '#3b4252',
    'FocusedButtonPressedForegroundColor': '#eceff4',
    'FocusedButtonActiveForegroundColor': '#eceff4',
    'FocusedButtonPressedBackgroundColor': '#434c5e',
    'FocusedButtonActiveBackgroundColor': '#434c5e',
    'ButtonFrameBorderColor': '#282e38',
    'SearchLabelForegroundColor': '#eceff4',
    'SearchLabelBackgroundColor': '#3b4252',
    'SearchLabelIconPath': './ui/search-nord.png',
    'RoundBoxPath': './ui/rounded-nord.png',
    'CanvasBackgroundColor': '#2e3440',
}
